# Generated by Django 5.0.6 on 2024-05-21 23:00

import seqfamapp.models
from django.db import migrations

# Exercise 3 - compress sequences (change sequence field to CompressedTextField)

"""
    Note:
    Something interesting happens when changing this field: the DB size increases.
    What's happening is that new freelist pages are being created as a result of updating the rows, 
    apparently being moved to new pages where they are store more adequately. Freepages are empty and can
    be reused lates, but they still take up size.

    Looking at the page_count, free_list_count and db size 
        - before the migration 
        - after the migration 
        - after the vacuum operation to restructure the DB (see migration 3)      
    makes this clearer.

    IMPORTANT: 
    I understand this doesn't happen if you apply the migrations all together, because the sequences
    are going to be loaded into the db after the CompressedTextField migration, meaning they will be already inserted in binary format.
    But this is what happened progressing through the exercise. 

    To reproduce what happened, you would need to:
        - comment the sequence = CompressedTextField line
        - decomment the sequence = models.TextField() line
        - apply the initial migration 0001
        - comment the sequence = models.TextField()
        - decomment sequence = CompressedTextField line
        - apply the second and third migration


    In both cases, the DB size gets shrunk from 2.1MB to 1.4MB
"""
from seqfamapp.management.utils import get_page_and_freelist_count

class Migration(migrations.Migration):

    dependencies = [
        ('seqfamapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_page_and_freelist_count),
        migrations.AlterField(
            model_name='uniprotkbentry',
            name='sequence',
            field=seqfamapp.models.CompressedTextField(blank=True, null=True),
        ),
        migrations.RunPython(get_page_and_freelist_count)
    ]
