# Generated by Django 5.0.6 on 2024-05-21 22:13

import seqfamapp.models
from django.db import migrations
from seqfamapp.management.utils import get_page_and_freelist_count
import zlib



 # Exercise 3 - Making sure that the alredy existing sequences are compressed
def compress_text(apps, schema_editor):    
    proteins = seqfamapp.models.UniProtKBEntry.objects.all()
    for protein in proteins:

        """
            This works because of the method get_prep_value defined CompressedTextField.
            It takes the already existing sequence string, encodes it in UTF-8 and compresses it.
        """
        
        if (protein.sequence):
            protein.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('seqfamapp', '0002_alter_uniprotkbentry_sequence'),
    ]

    operations = [
        migrations.RunPython(compress_text),
        migrations.RunPython(get_page_and_freelist_count),
        migrations.RunSQL("COMMIT; VACUUM;"),
        migrations.RunPython(get_page_and_freelist_count)
    ]